import random

first_names = ['Billie', 'Raymundo', 'Theodore', 'Markus', 'Enrique', 'Ramon', 'Bud', 'Micah', 'Emmett', 'Pat', 'Trent', 'Kerry', 'Frankie', 'Numbers', 'Royal', 'Isaac', 'Willie', 'Philip', 'Rudolph', 'Gustavo', 'Tomas', 'Robert', 'Chas', 'Truman', 'Burton', 'Clayton', 'Zachary', 'Williams', 'Joey', 'Edison', 'Manuel', 'Tyree', 'Carmen', 'Orlando', 'Stanley', 'Shayne', 'Marcellus', 'Dong', 'Dusty', 'Drew', 'Marcelo', 'Lesley', 'Del', 'Mitchel', 'Chris', 'Carey', 'Josh', 'Jess', 'Ellis', 'Harold', 'Rocco', 'Jae', 'Graig', 'Nicky', 'Vaughn', 'Loyd', 'Broderick', 'Irvin', 'Wilber', 'Dominick', 'Bud', 'Taylor', 'Gregg', 'Eddy', 'Robin', 'Jesse', 'Mathew', 'Gerardo', 'Adrian', 'Paul', 'Shannon', 'Margarito', 'Rashad', 'Walter', 'Gregorio', 'Jerold', 'Scot', 'Garfield', 'Bennett', 'Jake', 'Emery', 'Pasquale', 'Jimmie', 'Luke', 'Renato', 'Xavier', 'Rodger', 'Nathanial', 'Leonardo', 'Levi', 'Terrance', 'Chad', 'Harland', 'Kent', 'Deon', 'Fernando', 'Dana', 'Cornelius', 'Lenny', 'Arden', 'Shonna', 'Vina', 'Marleen', 'Roxana', 'Caryl', 'Chery', 'Anja', 'Teresa', 'Joelle', 'Elana', 'Ilana', 'Jonelle', 'Verla', 'Tiffiny', 'Shella', 'Temika', 'Jong', 'Merissa', 'Birgit', 'Willene', 'Veronika', 'Suzan', 'Florencia', 'Maris', 'Cristine', 'Lizbeth', 'Delena', 'Yvonne', 'Allie', 'Reita', 'Angelic', 'Kari', 'Yasuko', 'Natalie', 'Joyce', 'Jetta', 'Veronique', 'Marguerite', 'Vashti', 'Geraldine', 'Epifania', 'Ines', 'Shanti', 'Aurora', 'Doretha', 'Aleisha', 'Bernice', 'Catrina', 'Celesta', 'Renate', 'Amada', 'Aura', 'Nada', 'Erinn', 'Fabiola', 'Shan', 'Randi', 'Alpha', 'Mazie', 'Velvet', 'Shannan', 'Tracee', 'Deidre', 'Catarina', 'Valene', 'Verdie', 'Pinkie', 'Olympia', 'Rosina', 'Junita', 'Maurine', 'Holli', 'Aurelia', 'Yu', 'Leena', 'Kena', 'Genie', 'Gertie', 'Hermina', 'Mardell', 'Willia', 'Shiloh', 'Hollie', 'Michaela', 'Julie', 'Terese', 'Nadine', 'Maddie', 'Albina', 'Tia', 'Rasheeda', 'Jenee', 'Leeanna', 'Mildred', 'Shalonda', 'Milly', 'Starla', 'Rona', 'Le', 'Krysta']
last_names = ['Macarthur', 'Argento', 'Songer', 'Weimer', 'Bungard', 'Knauss', 'Burnam', 'Mangini', 'Woo', 'Mcanally', 'Sheahan', 'Sorber', 'Young', 'Favor', 'Dietz', 'North', 'Ehlert', 'Joslyn', 'Huskins', 'Boll', 'Stribling', 'Contreras', 'Weissinger', 'Wensel', 'Delapaz', 'Brunson', 'Borrelli', 'Austell', 'Hoffmeister', 'Goetzinger', 'Colegrove', 'Curiel', 'Rawson', 'Gengler', 'Oxner', 'Andrea', 'Pixley', 'Mceachern', 'Hartlage', 'Carrington', 'Cueto', 'Arenas', 'Brundidge', 'Meachum', 'Buck', 'Langlais', 'Gabor', 'Fisher', 'Boateng', 'Riemer', 'Drees', 'Ferdinand', 'Beltz', 'Kleinman', 'Crepeau', 'Mcandrew', 'Cantrelle', 'Strock', 'Leland', 'Demille', 'Pham', 'Taggart', 'Salzman', 'Collard', 'Schmid', 'Goldsborough', 'Weiland', 'Starns', 'Horner', 'Pasko', 'Bustillos', 'Schuld', 'Gladstone', 'Lung', 'Munos', 'Garrard', 'Mcneel', 'Kellett', 'Goodall', 'Mcintire', 'Purvis', 'Deese', 'Sterner', 'Kullman', 'Tootle', 'Malbrough', 'Ormond', 'Larimore', 'Peter', 'Mayhue', 'Buice', 'Frias', 'Holzinger', 'Foskey', 'Bergin', 'Greenman', 'Wommack', 'Paynter', 'Tone', 'Carron', 'Yancy', 'Pendley', 'Kimrey', 'Sergi', 'Scholl', 'Shuey', 'Audie', 'Bayley', 'Umstead', 'Sequeira', 'Pruett', 'Zeh', 'Navarrete', 'Scates', 'Clendening', 'Dam', 'Rohr', 'Straughan', 'Low', 'Saravia', 'Larger', 'Fernandez', 'Brookover', 'Jarvis', 'Wakeland', 'Farrel', 'Bergquist', 'Holford', 'Mahaney', 'Peterkin', 'Heng', 'Solt', 'Usry', 'Hassell', 'Suther', 'Babineau', 'Jelley', 'Davey', 'Herrell', 'Boros', 'Minarik', 'Almada', 'Riggenbach', 'Tousignant', 'Stoltz', 'Garriott', 'Zamor', 'Brophy', 'Houchins', 'Pereira', 'Guidotti', 'Andres', 'Wind', 'Greear', 'Randol', 'Rogowski', 'Mcnabb', 'Rolle', 'Bolding', 'Ranieri', 'Carra', 'Vanwart', 'Layden', 'Marlatt', 'Heimer', 'Cartee', 'Stebbins', 'Wescott', 'Swing', 'Robuck', 'Rancourt', 'Deremer', 'Gossard', 'Brunner', 'Messineo', 'Lemmon', 'Condra', 'Bergey', 'Nealy', 'Denker', 'Brubaker', 'Hopkin', 'Hopps', 'Phillip', 'Vess', 'Blundell', 'Durocher', 'Gosse', 'Horney', 'Montero', 'Corchado', 'Hundt', 'Moorhouse', 'Pursell', 'Kettering', 'Stolz', 'Bryden', 'Gholston', 'Vanover', 'Cowley']

def createRandomUser():
	result = {}
	result['nickname'] = first_names[random.randrange(0,199)]
	result['email'] =  result['nickname']+ str(random.randrange(10,99)) + '@gmail.com'
	result['password'] = 'password'
	return result

print createRandomUser()





